{% set name = "ittapi" %}
{% set version = "3.24.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4e6cb42b6bd9e699e3dfbaf678e572f4292127dfee3312744137ac567064a26f

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [linux]
# ittapi is a static library, so it has neither host nor run dependencies
test:
  commands:
    - dir %LIBRARY_INC%\ittnotify.h  # [win]
    - test -f ${PREFIX}/include/ittnotify.h  # [not win]

about:
  home: https://github.com/intel/ittapi
  license: GPL-2.0-only OR BSD-3-Clause
  license_file:
    - BSD-3-Clause.txt
    - GPL-2.0-only.txt
  summary: Intel® Instrumentation and Tracing Technology (ITT) and Just-In-Time (JIT) API
  description: |
    This ITT/JIT open source profiling API includes:
      - Instrumentation and Tracing Technology (ITT) API
      - Just-In-Time (JIT) Profiling API

    The Instrumentation and Tracing Technology (ITT) API enables your application to generate and control the collection of trace data during its execution across different Intel tools.

    ITT API consists of two parts: a static part and a dynamic part. The dynamic part is specific for a tool and distributed only with a particular tool. The static part is a common part shared between tools. Currently, the static part of ITT API is distributed as a static library and released under a BSD/GPLv2 dual license with every tool supporting ITT API.
  doc_url: https://github.com/intel/ittapi
  dev_url: https://github.com/intel/ittapi

extra:
  recipe-maintainers:
    - vnlitvinov
    - ekovanova
